# Generated by Django 4.0.4 on 2022-04-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoPinturasJJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sqm',
            field=models.FloatField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialbudget',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyectoPinturasJJ.material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='exists',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='materialbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoPinturasJJ.budget'),
        ),
    ]
